name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -GNinja

    - name: Linux Build
      run: cmake --build build --parallel $(nproc)

    - name: Build Directory Info
      continue-on-error: true
      run: find build -print | sed -e 's;[^/]*/;|──;g;s;──|; |;g'

    - name: Package
      run: |
        mkdir -p artifact
        cp build/Canistral artifact/
        tar czf Canistral-Linux.tar.gz artifact/*
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Canistral-Linux
        path: Canistral-Linux.tar.gz

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -GNinja

    - name: MacOS Build
      run: cmake --build build --parallel $(sysctl -n hw.ncpu)

    - name: Build Directory Info
      continue-on-error: true
      run: find build -print | sed -e 's;[^/]*/;|──;g;s;──|; |;g'

    - name: Package
      run: |
        mkdir -p artifact
        cp build/Canistral artifact/
        hdiutil create -volname Canistral -srcfolder artifact -ov Canistral-macOS.dmg
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Canistral-macOS
        path: Canistral-macOS.dmg

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -GNinja

    - name: Build
      run: cmake --build build --config Release --parallel 4

    - name: Build Directory Info
      continue-on-error: true
      shell: pwsh
      run: |
        Get-ChildItem -Path build -Recurse | ForEach-Object {
          $depth = $_.FullName.Split('\').Count - $PWD.Path.Split('\').Count - 1
          $indent = '    ' * $depth
          if ($_.PSIsContainer) {
              "$indent├── [$($_.Name)]"  # Directory marker
          } else {
              "$indent├── $($_.Name)"    # File
          }
        }

    - name: Package
      run: |
        mkdir artifact
        copy "build\Canistral.exe" artifact/
        copy "build\*.dll" artifact/
        7z a "Canistral-Windows.zip" artifact/*
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Canistral-Windows
        path: Canistral-Windows.zip
