name: Linux Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sh scripts/install_linux.sh

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -GNinja

    - name: Build
      run: cmake --build build --parallel $(nproc)

    - name: Package
      run: |
        mkdir -p artifact
        cp build/Canistral artifact/
        tar czf Canistral-Linux.tar.gz artifact/*
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Canistral-Linux
        path: Canistral-Linux.tar.gz